### ISSUE TITLE
Could not initialize class com.olliez4.interface4.util.hologram.DebugMarker

### ISSUE THREAD

**Issue by addpromax** [Z4OLLIEZ4/Space#15]
[Space] Task #44 for Space v2.11.4 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.olliez4.interface4.util.hologram.DebugMarker
	at com.olliez4.space.managers.CustomItemManager$1.run(CustomItemManager.java:188) ~[Space 2.11.4.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0 [in thread "Server thread"]
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:315) ~[ProtocolLib.jar:?]
	at com.olliez4.interface4.util.hologram.DebugMarker.<clinit>(DebugMarker.java:193) ~[Interface4 (1).jar:?]
	... 9 more

**Comment by Z4OLLIEZ4** [comment]
Resolved in latest
Please open a ticket on the discord server in future rather than using the wiki for support
Thank you :)
